### ISSUE TITLE
Nested json resource

### ISSUE THREAD

**Issue by jchapelle** [traverson/traverson#131]
I can't find in the documentation how to only convert a part of the json response ?
E.g. : Assume you get this json as a response from a rest call, how to convert the myResources to an java object ?
```
{
...
   _embedded: {
      myResources: [
     ]
   }
...
}
```

**Comment by basti1302** [comment]
Hi,

I assume you are doing something like 

```
traverson
.from('http://api.example.com')
.follow('link_to', 'something')
.getResource(function(error, resource) {
   ...
```

to fetch a resource after following a number of links.

There is no special API to only get _a part of the resource_. It wouldn't add much benefit anyway. The server will send the whole resource anyway and Traverson would also need to convert all of it to JSON. So to only get a part of the resource, you can just work with the deserialized object that Traverson gives you like you would do with any JavaScript object.

Since your example looks like HAL, this is a slightly different case. If the last link you pass to `.follow` is `myResources`, traverson-hal will also check for an embedded resource of that name and give it to you.

Finally, you asked "how to convert the myResources to an **_java_** object?" - I'm wondering if the "Java" there is just a typo (in this case, nevermind) or if you are actually working with Java - in this case you have probably ended up opening the issue in the wrong repo, because this is a **JavaScript** library. As far as I know there are Java ports of Traverson out there. The most popular is probably included in the https://github.com/spring-projects/spring-hateoas project (https://docs.spring.io/spring-hateoas/docs/current/reference/html/#client.traverson).

**Comment by jchapelle** [comment]
Oh sorry, It seems I am not in the proper repo.
Thanks for your precise answer.
